# Generated by Django 4.2.11 on 2024-08-15 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Title', models.CharField(blank=True, max_length=150, null=True)),
                ('BookPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('BookImage', models.ImageField(blank=True, null=True, upload_to='media/HomePage')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Add A New Book',
                'verbose_name_plural': 'Add A New Book',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Title', models.CharField(blank=True, max_length=150, null=True)),
                ('BookImage', models.ImageField(blank=True, null=True, upload_to='media/HomePage')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Book Post',
                'verbose_name_plural': ' Book Post ',
            },
        ),
        migrations.CreateModel(
            name='FabaritBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='HomePage.addnewbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Fabarit Book',
                'verbose_name_plural': ' Fabarit Book ',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
