# Generated by Django 4.2.11 on 2024-08-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addnewbook',
            name='BookPrice',
        ),
    ]
