# Generated by Django 4.2.11 on 2024-08-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_remove_addnewbook_bookprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
